apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel
  namespace: microservices
  labels:
    app: sentinel
    tier: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      labels:
        app: sentinel
        tier: microservices
    spec:
      containers:
        - name: sentinel
          image: messagewall-microservice:latest
          imagePullPolicy: Never
          env:
            - name: SERVICE_NAME
              value: sentinel
            - name: LOG_INTERVAL
              value: "45"
          resources:
            requests:
              memory: "16Mi"
              cpu: "5m"
            limits:
              memory: "32Mi"
              cpu: "10m"
