apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel
  namespace: platform-ops-prod
  labels:
    app: sentinel
    app.kubernetes.io/part-of: order-platform
    team: platform-ops
    environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      labels:
        app: sentinel
        app.kubernetes.io/part-of: order-platform
        team: platform-ops
        environment: prod
    spec:
      containers:
        - name: sentinel
          image: messagewall-microservice:latest
          imagePullPolicy: Never
          env:
            - name: SERVICE_NAME
              value: sentinel
            - name: LOG_INTERVAL
              value: "45"
          resources:
            requests:
              memory: "16Mi"
              cpu: "5m"
            limits:
              memory: "32Mi"
              cpu: "10m"
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: true
