# DynamoDB table for messagewall-east
# Region: us-east-1
---
apiVersion: dynamodb.aws.upbound.io/v1beta2
kind: Table
metadata:
  name: messagewall-east-table
  annotations:
    crossplane.io/external-name: messagewall-east-205074708100
spec:
  forProvider:
    region: us-east-1
    billingMode: PAY_PER_REQUEST
    hashKey: PK
    rangeKey: SK
    attribute:
      - name: PK
        type: S
      - name: SK
        type: S
  providerConfigRef:
    name: default
