apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  namespace: customer-dev
  labels:
    app: weather
    app.kubernetes.io/part-of: order-platform
    team: customer
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
        app.kubernetes.io/part-of: order-platform
        team: customer
        environment: dev
    spec:
      containers:
        - name: weather
          image: messagewall-microservice:latest
          imagePullPolicy: Never
          env:
            - name: SERVICE_NAME
              value: weather
            - name: LOG_INTERVAL
              value: "60"
          resources:
            requests:
              memory: "16Mi"
              cpu: "5m"
            limits:
              memory: "32Mi"
              cpu: "10m"
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: true
