apiVersion: apps/v1
kind: Deployment
metadata:
  name: heartbeat
  namespace: platform-ops-dev
  labels:
    app: heartbeat
    app.kubernetes.io/part-of: order-platform
    team: platform-ops
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heartbeat
  template:
    metadata:
      labels:
        app: heartbeat
        app.kubernetes.io/part-of: order-platform
        team: platform-ops
        environment: dev
    spec:
      containers:
        - name: heartbeat
          image: messagewall-microservice:latest
          imagePullPolicy: Never
          env:
            - name: SERVICE_NAME
              value: heartbeat
            - name: LOG_INTERVAL
              value: "30"
          resources:
            requests:
              memory: "16Mi"
              cpu: "5m"
            limits:
              memory: "32Mi"
              cpu: "10m"
