# S3 Bucket for messagewall-west static website hosting and Lambda artifacts
# Region: us-west-2
---
apiVersion: s3.aws.upbound.io/v1beta2
kind: Bucket
metadata:
  name: messagewall-west-bucket
  annotations:
    crossplane.io/external-name: messagewall-west-205074708100
spec:
  forProvider:
    region: us-west-2
  providerConfigRef:
    name: default
---
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketOwnershipControls
metadata:
  name: messagewall-west-bucket-ownership
spec:
  forProvider:
    region: us-west-2
    bucketRef:
      name: messagewall-west-bucket
    rule:
      - objectOwnership: BucketOwnerEnforced
  providerConfigRef:
    name: default
---
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketPublicAccessBlock
metadata:
  name: messagewall-west-bucket-public-access
spec:
  forProvider:
    region: us-west-2
    bucketRef:
      name: messagewall-west-bucket
    blockPublicAcls: false
    blockPublicPolicy: false
    ignorePublicAcls: false
    restrictPublicBuckets: false
  providerConfigRef:
    name: default
---
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketWebsiteConfiguration
metadata:
  name: messagewall-west-bucket-website
spec:
  forProvider:
    region: us-west-2
    bucketRef:
      name: messagewall-west-bucket
    indexDocument:
      - suffix: index.html
    errorDocument:
      - key: error.html
  providerConfigRef:
    name: default
---
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketCorsConfiguration
metadata:
  name: messagewall-west-bucket-cors
spec:
  forProvider:
    region: us-west-2
    bucketRef:
      name: messagewall-west-bucket
    corsRule:
      - allowedHeaders:
          - "*"
        allowedMethods:
          - GET
          - POST
        allowedOrigins:
          - "*"
        exposeHeaders:
          - ETag
        maxAgeSeconds: 3000
  providerConfigRef:
    name: default
---
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketPolicy
metadata:
  name: messagewall-west-bucket-policy
spec:
  forProvider:
    region: us-west-2
    bucketRef:
      name: messagewall-west-bucket
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::messagewall-west-205074708100/*"
          }
        ]
      }
  providerConfigRef:
    name: default
