# Crossplane function-patch-and-transform
# Required for Pipeline mode Compositions
# See: https://github.com/crossplane-contrib/function-patch-and-transform
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.7.0
