# ServerlessEventApp Claim for prod environment
# Deploys all 17 AWS resources for the message wall demo
#
# This example shows production settings with:
#   - Higher Lambda memory for better performance
#   - Longer timeout for reliability
#   - Precious resource annotations for delete/destroy protection
#
# Prerequisites:
#   - MessageWallRoleBoundary IAM policy must exist in AWS
#   - Lambda artifacts must be uploaded to S3 (artifacts/api-handler.zip, artifacts/snapshot-writer.zip)
#
# Usage:
#   kubectl apply -f messagewall-prod.yaml
#   kubectl get serverlesseventappclaim messagewall-prod -w
#
# Verify:
#   kubectl get managed -l crossplane.io/claim-name=messagewall-prod
#
# Protection:
#   This Claim contains precious resources (DynamoDB, S3) with customer data.
#   Delete/destroy operations require explicit approval per EPIC-17.
#   See docs/precious-resources.md for details.
---
apiVersion: messagewall.demo/v1alpha1
kind: ServerlessEventAppClaim
metadata:
  name: messagewall-prod
  namespace: default
  annotations:
    # Precious resource protection (EPIC-17)
    confighub.io/precious: "true"
    confighub.io/precious-resources: "dynamodb,s3"
    confighub.io/data-classification: "customer-data"
    # Gate enforcement
    confighub.io/delete-gate: "enabled"
    confighub.io/destroy-gate: "enabled"
spec:
  # Required fields
  environment: prod
  awsAccountId: "123456789012"  # Replace with your AWS account ID

  # Production settings
  resourcePrefix: messagewall
  region: us-east-1
  lambdaMemory: 256    # Higher memory for production
  lambdaTimeout: 30    # Longer timeout for reliability
  eventSource: messagewall.api-handler
