apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmp-confighub
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: confighub
    spec:
      # Note: Omitting 'version' so socket is named 'confighub.sock' not 'confighub-v1.0.sock'

      # Discovery: identify when this plugin should be used
      # Always return true since this plugin is explicitly requested via source.plugin.name
      # The actual ConfigHub space is specified via source.plugin.env.CONFIGHUB_SPACE
      discover:
        find:
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Always match - this plugin is explicitly requested in Application spec
              # The git repo is just a placeholder; actual content comes from ConfigHub
              echo "confighub"

      # Init: authenticate with ConfigHub as a worker
      init:
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Initializing ConfigHub CMP..."
            if [ -z "$CONFIGHUB_WORKER_ID" ] || [ -z "$CONFIGHUB_WORKER_SECRET" ]; then
              echo "Warning: ConfigHub credentials not configured"
              echo "Run scripts/setup-argocd-confighub-auth.sh to configure"
              exit 0
            fi

            # Retry auth with exponential backoff (handles transient config/network issues)
            MAX_RETRIES=3
            RETRY_DELAY=1
            for i in $(seq 1 $MAX_RETRIES); do
              if cub auth login --as-worker 2>&1; then
                exit 0
              fi
              if [ $i -lt $MAX_RETRIES ]; then
                echo "Auth attempt $i failed, retrying in ${RETRY_DELAY}s..."
                sleep $RETRY_DELAY
                RETRY_DELAY=$((RETRY_DELAY * 2))
              fi
            done
            echo "Error: Failed to authenticate after $MAX_RETRIES attempts"
            exit 1

      # Generate: fetch all units from ConfigHub space at their HeadRevisionNum
      # For pull-based sync with ArgoCD, we fetch the latest pushed revision.
      # This is appropriate when ConfigHub is used as a config store without
      # a separate promotion workflow (LiveRevisionNum requires targets).
      generate:
        command: ["/bin/sh", "-c"]
        args:
          - |
            # ArgoCD passes Application env vars with ARGOCD_ENV_ prefix
            SPACE="${ARGOCD_ENV_CONFIGHUB_SPACE:-$CONFIGHUB_SPACE}"

            if [ -z "$SPACE" ]; then
              echo "Error: CONFIGHUB_SPACE not set (check Application spec source.plugin.env)" >&2
              exit 1
            fi

            if [ -z "$CONFIGHUB_WORKER_ID" ]; then
              echo "# ConfigHub credentials not configured"
              echo "# Run scripts/setup-argocd-confighub-auth.sh to configure"
              exit 0
            fi

            # Authenticate before fetching (auth token may have expired)
            # Retry with brief delay if first attempt fails
            cub auth login --as-worker >/dev/null 2>&1 || {
              sleep 1
              cub auth login --as-worker >/dev/null 2>&1
            }

            # Fetch each unit's content at its HeadRevisionNum (latest pushed revision)
            # For pull-based ArgoCD sync, we use Head since Live requires targets.
            cub unit list --space "$SPACE" --no-header \
              --columns Unit.Slug,Unit.HeadRevisionNum 2>/dev/null | while read -r unit head_rev; do
              if [ -n "$unit" ] && [ -n "$head_rev" ] && [ "$head_rev" != "0" ]; then
                cub revision get --space "$SPACE" --data-only "$unit" "$head_rev" 2>/dev/null
                echo "---"
              fi
            done
